### ISSUE TITLE
Building causalml from source failure: UnicodeDecodeError

### ISSUE THREAD

**Issue by snjie209** [uber/causalml#224]
**Describe the bug**
I am trying to install causalml by building it from source and following your instructions.

I spun up a docker container with these configurations and am working inside of that.

**To Reproduce**
To reproduce, follow instructions from main page to build from source: https://github.com/uber/causalml

Install from source:

$ git clone https://github.com/uber/causalml.git
$ cd causalml
$ python3.6 setup.py build_ext --inplace

I encounter the error after the above step.

**Expected behavior**
```
bash-4.2# python3.6 setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    long_description = f.read()
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9546: ordinal not in range(128)
```
**Screenshots**

**Environment (please complete the following information):**
 - OS: Oracle Linux 7
 - Python Version: 3.6]

**Additional context**

**Comment by snjie209** [comment]
Actually I had to change my encoding to UTF-8 per https://stackoverflow.com/questions/52419117/not-able-to-read-file-due-to-unicode-error-in-python. Which solved it for me.
