### ISSUE TITLE
TypeError: evaluate_CTS() got an unexpected keyword argument 'control_name'

### ISSUE THREAD

**Issue by bubble-wu** [uber/causalml#423]
**Describe the bug**
when fitting model
```python
    uplift_model = UpliftRandomForestClassifier(control_name='control', 
                                                max_features=max_features, 
                                                max_depth=max_depth,
                                                n_estimators=n_estimators,
                                                n_reg=n_reg,
                                                n_jobs=4)


    print(".....start training model, exp" + str(cv))
    uplift_model.fit(X=df_train[features].values,
                 treatment=df_train['treatment_group_key'].values,
                 y=df_train['outcome'].values)
```
I encountered this error.

```
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/home/admin/.local/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/admin/.local/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/home/admin/.local/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/home/admin/.local/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/admin/.local/lib/python3.6/site-packages/causalml/inference/tree/models.py", line 1298, in bootstrap
    tree.fit(X=x_train_bt, treatment=treatment_train_bt, y=y_train_bt)
  File "/home/admin/.local/lib/python3.6/site-packages/causalml/inference/tree/models.py", line 192, in fit
    n_reg=self.n_reg, parentNodeSummary=None
  File "/home/admin/.local/lib/python3.6/site-packages/causalml/inference/tree/models.py", line 900, in growDecisionTreeFrom
    currentScore = evaluationFunction(currentNodeSummary, control_name=self.control_name)
TypeError: evaluate_CTS() got an unexpected keyword argument 'control_name'
"""
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
version 0.11.0

**Additional context**

**Comment by jeongyoonlee** [comment]
From the code, it seems that you're using `v0.10.0` instead of `v0.11.1`. Could you update `causalml` and see if it works.

**Comment by bubble-wu** [comment]
> From the code in the error message, it seems that you're using `v0.10.0` instead of `v0.11.1`. Could you update `causalml` and see if it works.

Thanks for your reply, I tired with v0.11.0 and still got the same error.
I checked the source code and find that function `evaluate_CTS` has args `control_name` in its comment but with it when  declaring it, does it matter?
```python
    @staticmethod
    def evaluate_CTS(currentNodeSummary):
        '''
        Calculate CTS (conditional treatment selection) as split evaluation criterion for a given node.

        Args
        ----
        nodeSummary : dictionary
            The tree node summary statistics, produced by tree_node_summary() method.

        control_name : string
            The control group name.

        Returns
        -------
        d_res : Chi-Square
        '''
        mu = 0.0
        # iterate treatment group
        for r in currentNodeSummary:
            mu = max(mu, currentNodeSummary[r][0])
        return -mu
```
```
staticevaluate_Chi(nodeSummary, control_name)[source]¶
Calculate Chi-Square statistic as split evaluation criterion for a given node.

Parameters
nodeSummary (dictionary) – The tree node summary statistics, produced by tree_node_summary() method.

control_name (string) – The control group name.

Returns
d_res

Return type
Chi-Square
```

**Comment by jeongyoonlee** [comment]
Could you update it to v0.11.1? One of the differences between v0.11.0 and v0.11.1 is that in v0.11.1, the default evaluationFunction is set to 'KL' instead of 'CTS'. 

Also we're removing control_name from all evaluationFuntion in PR #422, so you will not have this problem once we merge it. 

Thanks for trying.

**Comment by jeongyoonlee** [comment]
#422 got merged into `master`. Could you install `causalml` from the latest `master` and try it?
```bash
$ pip install -U git+https://github.com/uber/causalml.git@master
```

**Comment by bubble-wu** [comment]
> #422 got merged into `master`. Could you install `causalml` from the latest `master` and try it?
> 
> ```shell
> $ pip install -U git+https://github.com/uber/causalml.git@master
> ```

It works fine for this latest version. Thanks a lot!
