### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by ieriii** [uber/causalml#525]
I have installed causalml in the past (e.g. last month) and everything worked fine.
However, today I got the error below when install using pip. I've also tried to use conda but I got the error no packaged found.

Anyone has any suggestions? Thank you.

```
Pip subprocess output:
Collecting causalml==0.12.3
  Using cached causalml-0.12.3.tar.gz (406 kB)

Pip subprocess error:
    ERROR: Command errored out with exit status 1:
     command: /home/user/miniconda3/envs/xxx-xxx/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-god_8o8u/causalml_8581e382aa6c47ba92ce0fe612652b74/setup.py'"'"'; __file__='"'"'/tmp/pip-install-god_8o8u/causalml_8581e382aa6c47ba92ce0fe612652b74/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-6x0os9ek
         cwd: /tmp/pip-install-god_8o8u/causalml_8581e382aa6c47ba92ce0fe612652b74/
    Complete output (58 lines):
    /home/user/miniconda3/envs/xxx-xxx/lib/python3.9/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
      warnings.warn(
    /tmp/pip-install-god_8o8u/causalml_8581e382aa6c47ba92ce0fe612652b74/.eggs/Cython-0.29.30-py3.9-linux-x86_64.egg/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-god_8o8u/causalml_8581e382aa6c47ba92ce0fe612652b74/causalml/inference/tree/causaltree.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)

    Error compiling Cython file:
    ------------------------------------------------------------
    ...

        cdef double node_impurity(self) nogil:
            """Evaluate the impurity of the current node, i.e. the impurity of
               samples[start:end]."""

            cdef double* sum_total = self.sum_total
                                        ^
    ------------------------------------------------------------

    causalml/inference/tree/causaltree.pyx:77:37: Cannot assign type 'double[::1]' to 'double *'

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            cdef SIZE_t* samples = self.samples
            cdef SIZE_t start = self.start
            cdef SIZE_t pos = self.pos
            cdef SIZE_t end = self.end

            cdef double* sum_left = self.sum_left
                                       ^
    ------------------------------------------------------------

    causalml/inference/tree/causaltree.pyx:135:36: Cannot assign type 'double[::1]' to 'double *'

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            cdef SIZE_t start = self.start
            cdef SIZE_t pos = self.pos
            cdef SIZE_t end = self.end

            cdef double* sum_left = self.sum_left
            cdef double* sum_right = self.sum_right
                                        ^
    ------------------------------------------------------------

    causalml/inference/tree/causaltree.pyx:136:37: Cannot assign type 'double[::1]' to 'double *'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-god_8o8u/causalml_8581e382aa6c47ba92ce0fe612652b74/setup.py", line 71, in <module>
        ext_modules=cythonize(extensions, annotate=True),
      File "/tmp/pip-install-god_8o8u/causalml_8581e382aa6c47ba92ce0fe612652b74/.eggs/Cython-0.29.30-py3.9-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1127, in cythonize
        cythonize_one(*args)
      File "/tmp/pip-install-god_8o8u/causalml_8581e382aa6c47ba92ce0fe612652b74/.eggs/Cython-0.29.30-py3.9-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1250, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: causalml/inference/tree/causaltree.pyx
    Compiling causalml/inference/tree/causaltree.pyx because it depends on /tmp/pip-install-god_8o8u/causalml_8581e382aa6c47ba92ce0fe612652b74/.eggs/Cython-0.29.30-py3.9-linux-x86_64.egg/Cython/Includes/libc/string.pxd.
    Compiling causalml/inference/tree/uplift.pyx because it depends on /tmp/pip-install-god_8o8u/causalml_8581e382aa6c47ba92ce0fe612652b74/.eggs/Cython-0.29.30-py3.9-linux-x86_64.egg/Cython/Includes/libc/string.pxd.
    [1/2] Cythonizing causalml/inference/tree/causaltree.pyx
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/1c/9a/c1ca74f072b8ee4472820c7f0f97fedf82a2d3123118c9d2818988f4f146/causalml-0.12.3.tar.gz#sha256=4d85afa0590e4c60818311c2be9a5be64b8c6964b134c77654b738df551454fa (from https://pypi.org/simple/causalml/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement causalml==0.12.3 (from versions: 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.7.1, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.11.1, 0.12.0, 0.12.1, 0.12.2, 0.12.3)
ERROR: No matching distribution found for causalml==0.12.3

failed

```

**Comment by ieriii** [comment]
Here is the error when using conda (and conda-forge channel):
```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - causalml
```

**Comment by guotong1988** [comment]
same problem
