### ISSUE TITLE
Unable to install the package

### ISSUE THREAD

**Issue by bhav09** [uber/causalml#643]
**Describe the bug**
I am facing issues in installing the package. I have tried lower versions too but the issue persists. 

**To Reproduce**
```pip install causalml``` or ```conda install -c conda-forge causalml``` 

**Expected behaviour**
Should install the package

**Environment (please complete the following information):**
 - OS: Debian
 - Python Version: 3.10.8
 - Versions of Major Dependencies  `pandas==1.4.4`, `scikit-learn==1.1.3`, `cython==0.29.36`

**Additional context**
This is the error log: 
`pip install causalml`
```
Collecting causalml
  Using cached causalml-0.14.0.tar.gz (899 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      warning: /tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/sklearn/tree/_tree.pxd:61:73: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: /tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/sklearn/tree/_tree.pxd:62:59: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: /tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/sklearn/tree/_tree.pxd:63:63: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: /tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/sklearn/tree/_splitter.pxd:84:72: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: /tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/sklearn/tree/_splitter.pxd:89:68: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: /tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/sklearn/tree/_criterion.pxd:57:45: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: /tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/sklearn/tree/_criterion.pxd:58:40: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: /tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/sklearn/tree/_criterion.pxd:59:48: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: /tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/sklearn/tree/_criterion.pxd:60:57: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: /tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/sklearn/tree/_utils.pxd:49:75: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: /tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/sklearn/tree/_utils.pxd:87:61: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: /tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/sklearn/tree/_utils.pxd:119:56: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: /tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/sklearn/tree/_utils.pxd:137:40: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: /tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/sklearn/tree/_utils.pxd:139:71: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: /tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/sklearn/tree/_utils.pxd:160:71: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: /tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/sklearn/tree/_utils.pxd:161:40: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: /tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/sklearn/neighbors/_quad_tree.pxd:72:59: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: /tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/sklearn/neighbors/_quad_tree.pxd:91:51: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: /tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/sklearn/neighbors/_quad_tree.pxd:94:59: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: /tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/sklearn/neighbors/_quad_tree.pxd:95:63: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: /tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/sklearn/neighbors/_quad_tree.pxd:96:80: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: causalml/inference/tree/causal/_builder.pyx:185:71: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      warning: causalml/inference/tree/causal/_builder.pyx:331:76: The keyword 'nogil' should appear at the end of the function signature line. Placing it before 'except' or 'noexcept' will be disallowed in a future version of Cython.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
              # Initial capacity
              cdef int init_capacity
      
              if tree.max_depth <= 10:
                  init_capacity = (2 ** (tree.max_depth + 1)) - 1
                                                              ^
      ------------------------------------------------------------
      
      causalml/inference/tree/causal/_builder.pyx:61:56: Cannot assign type 'double' to 'int'
      Compiling causalml/inference/tree/causal/_criterion.pyx because it changed.
      Compiling causalml/inference/tree/causal/_builder.pyx because it changed.
      Compiling causalml/inference/tree/uplift.pyx because it changed.
      [1/3] Cythonizing causalml/inference/tree/causal/_builder.pyx
      Traceback (most recent call last):
        File "/opt/conda/miniconda3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/conda/miniconda3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/conda/miniconda3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 46, in <module>
        File "/tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-np5eb1q2/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: causalml/inference/tree/causal/_builder.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by goto-loop** [comment]
Same problem here when trying to install with pip and Python 3.7.12.

I am able to install the package if I use `causalml==0.13.0` though.

**Comment by fverac** [comment]
I was having the same issue and using `causalml==0.13.0` didn't work for me, seems to be related to recent changes to Cython. There are some recent commits in the causalml master branch addressing this issue. 

Installing it this way from a fresh clone of the repo works for me now: 
```
git clone https://github.com/uber/causalml
cd causalml
pip install -e .
```

**Comment by jeongyoonlee** [comment]
As @fverac mentioned, it's due to the changes in the latest Cython. This issue was fixed in #640 and will be included in a new release soon.

**Comment by bhav09** [comment]
Thanks for your response, @jeongyoonlee 👍

**Comment by vincewu51** [comment]
close this for now
